//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanIt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Club_member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Club_member()
        {
            this.Events_has_Member = new HashSet<Events_has_Member>();
        }
    
        public int idClub_members { get; set; }
        
        public int Positions_idPositions { get; set; }
        public int Student_idStudent { get; set; }
        public int Club_idClub { get; set; }
    
        public virtual Club Club { get; set; }
        [DisplayName("Position")]
        public virtual Position Position { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events_has_Member> Events_has_Member { get; set; }
    }
}
